FROM node:20-alpine

WORKDIR /app

# Esto es un placeholder. Cuando el Frontend (Joaquín) inicialice Angular:
# 1. Copia package.json y haz npm install
# 2. Expón el puerto 4200
# 3. Arranca "ng serve --host 0.0.0.0"

CMD ["sh", "-c", "echo 'Frontend Angular Container Inicializado. Pendiente de implementación por Joaquín.' && tail -f /dev/null"]
