version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mediolike-db
    restart: always
    environment:
      POSTGRES_USER: mediolike_user
      POSTGRES_PASSWORD: mediolike_password
      POSTGRES_DB: mediolike
    ports:
      - '5432:5432'
    volumes:
      - mediolike_pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mediolike_pgdata:
